### ISSUE TITLE
[BUG] can't SIGINT when using library

### ISSUE THREAD

**Issue by victorperin** [autolotto/bunnyhop#10]
Seems to relate with this bug here:
https://github.com/jprichardson/node-death/issues/7

**Comment by victorperin** [comment]
After SIGINT, I aways get this error:
```
IllegalOperationError: Channel closed
     at Channel.<anonymous (/usr/src/app/node_modules/amqplib/lib/channel.js:149:11)
     at Channel.C.reject (/usr/src/app/node_modules/amqplib/lib/channel_model.js:244:8)
     at Timeout.msg.reject [as _onTimeout] (/usr/src/app/node_modules/@autolotto/bunnyhop/build/lib/engines/default.engine.js:208:18)
     at ontimeout (timers.js:436:11)
     at tryOnTimeout (timers.js:300:5)
     at listOnTimeout (timers.js:263:5)
     at Timer.processTimers (timers.js:223:10)
```

**Comment by victorperin** [comment]
I think we can use this package as alternative:
https://github.com/jtlapp/node-cleanup

**Comment by victorperin** [comment]
I think this comment on node-death is a good way to start.

Try this:
```
const onDeathCallback = () => {
    try {
        shutdownRedis();
        logInfo('Redis');
        shutdownMongoose();
        logInfo('Mongo');
    } catch (err) {
        logError('death.config.onDeathCallback', 'ERR_GRACEFUL_CONN_SHUTDOWN', err);
    }
};
```

_Originally posted by @ukrbublik in https://github.com/jprichardson/node-death/issues/7#issuecomment-535518378_
